### ISSUE TITLE
install kaldi and Visal Studio 2017 

### ISSUE THREAD

**Issue by problemSolvingProgramming** [alvaromongon/windows-csharp-vosk-api#1]
Hi . Do I need to install  kaldi and ...... for  install vosk api or not?

The second question is whether this code will be compiled in Visal Studio 2017 or not?

**Comment by alvaromongon** [comment]
You need to install Vosk api for Python. Please, take a look at the readme.md file and follow the steps. You have a link in the readme.md to the Vosk api installation instructions page.

About Vs 2017. I did not try so I cannot be 100% sure. But if you have the targeted frameworks I do not see why know.

In general, I would recommend you getting Vs 2019. They have a free edition and it works much better than previous versions.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon Thank you very much for your explanation.

I followed the instructions you wrote, but unfortunately I got this error. On the right side of the dependentics visual studio, I see a yellow mark or error. How do I fix this?

![79204aac-aa6e-44ee-bc01-20defa27339c](https://user-images.githubusercontent.com/20268490/104928931-7ebb7100-59b8-11eb-811b-9bec50f0f03e.jpg)

**Comment by alvaromongon** [comment]
By the error I would say that you have re-targeted the projects and now they do not compile. You have to honour the frameworks I am targeting if you want it to work. If you don't have the frameworks installed in your local machine, you have to. I believe I have targeted net standard 2.1 and net 5.0. but to be sure, take a look at the csproj files. You have there the targets.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  hank you . I installed Visual Studio 2019 and followed your instructions, but unfortunately I see this line on the right.

![fe187565-e284-4fce-a920-a115f62cdf0e](https://user-images.githubusercontent.com/20268490/105047621-cce77780-5a7f-11eb-8335-4eba2a69bdae.jpg)

**Comment by alvaromongon** [comment]
You need to show the error messages. I cannot see anything there.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  
Hi, I managed to run the program, but unfortunately it only receives sound through the microphone and saves it in a file. If my goal is to display the sound taken through the microphone in text format realtime. 
![Untitled](https://user-images.githubusercontent.com/20268490/105138653-707d6a00-5b0a-11eb-9541-a39b40950006.png)

**Comment by alvaromongon** [comment]
So, where you able to press F2, record something from microphone and see what you recorded displayed in the console app?

In the screen shot you sent to me you have not press F2 to start recording anything.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  
Hi. I press the  f2. key. Records something and puts it in the folder wavefile but does not display.
![4e316676-cacd-4f8d-9273-858af128be8e](https://user-images.githubusercontent.com/20268490/105162650-2905d680-5b28-11eb-806c-cdf80032daa4.jpg)

![233](https://user-images.githubusercontent.com/20268490/105162837-5eaabf80-5b28-11eb-9eb7-5d56b5d3ad15.png)

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  i'm looking for the microphone to show the text online when I say something or at the same time.
![1455](https://user-images.githubusercontent.com/20268490/105162990-931e7b80-5b28-11eb-89dc-934b889071dd.png)

**Comment by alvaromongon** [comment]
so it look like vosk could not understand what you said. If you debug the code and are sure the python script is running, that might be the issue. Send me the wav file and I can double check for you.

Which vosk model are you using?

**Comment by problemSolvingProgramming** [comment]
@alvaromongon thank you . Yes, I will definitely send you the file. The model I used is vosk-model-small-fa-0.5  Persian 

or 
English model 

vosk-model-en-us-aspire-0.2 


sample test persian 
[test.zip](https://github.com/alvaromongon/windows-csharp-vosk-api/files/5842025/test.zip)

**Comment by alvaromongon** [comment]
So, In case you did not try yet. You should try to run the vosk api example as I suggested in the readme.md file. The information about how to do it is in the vosk installation instructions page (https://alphacephei.com/vosk/install), check the **Usage Examples** section.

you can first try with the english model and the wav file they provide and if it works try with any model and wav files you have.

I tried with the wav file you sent to me:
- With english model it does not recognize anything
- With Persian model it does recognize something but I do not have that set of characters installed. 

Try to do this yourself and first try in english, because my example program was not mean to use persian characters and I have no idea how it will behave.

Once you have tested an english wav file using vosk python, try the same using my solution. If it does not work, then we can take a look. But please, try all this yourself first.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  Hi, I tried what you said, I used the English model, but unfortunately I do not know exactly whether this method of using my model is correct or not? The model you used in the ..... section contains the following files: 
![45566666](https://user-images.githubusercontent.com/20268490/105569862-b29cea80-5d5a-11eb-82c4-53b5f4d394c5.png)

If the English model I used contains the following files. But unfortunately I could not get the output, I do not know if the method of using my model is wrong.

![1455555](https://user-images.githubusercontent.com/20268490/105569875-d7915d80-5d5a-11eb-85c2-6a274aa93bd4.png)

**Comment by alvaromongon** [comment]
Did you try with Python and it worked or not? 

Check I am talking about vosk python installation that is a dependency of my solution but independent.

About the files of the model. I have no idea. You should ask in vosk project.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  Yes, I tried, but unfortunately it does not work, it only saves the wave file It does not display text.

**Comment by alvaromongon** [comment]
Again, I asked you to try the vosk API python examples that take a wav file and run the same my solution run.

By your answer I believe you are trying work my solution. 

Could you please try using just vosk api as in the examples?

**Comment by problemSolvingProgramming** [comment]
@alvaromongon  
thank you . Do you mean to come and use the following example and replace it with a folder?
https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py

![788999999](https://user-images.githubusercontent.com/20268490/105579159-00851300-5d9a-11eb-99be-ca7ff40795d9.png)
